language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script: travis_wait coverage run --source=whooshstore -m unittest discover -v tests/ "*test.py"
after_success:
  coveralls
